services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER:-dev}
    image: aomr/ros2-humble:latest
    container_name: ros2-humble-dev
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - ./:/root/ros2_ws/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    user: "0:0"
    working_dir: /root
    privileged: false
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: tail -f /dev/null


