# Orbit Planner Parameters

# Update rates
map_update_rate: 2.0
planning_rate: 1.0

# Robot parameters
robot_radius: 0.4
safety_margin: 0.1

# Exploration parameters
max_planning_distance: 50.0
frontier_cluster_min_size: 5.0
frontier_cluster_max_distance: 10.0
goal_tolerance: 1.0

# Cost weights
yaw_change_weight: 0.5
frontier_gain_weight: 1.0
distance_weight: 1.0

# Tree detection parameters
tree_height_min: 0.4
tree_height_max: 0.7
tree_cluster_tolerance: 0.5
tree_min_cluster_size: 10

# Orbit anchor parameters
orbit_radius: 2.0
orbit_spacing: 1.0

# Path planning parameters
path_resolution: 0.1
path_smoothing_factor: 0.5

# Voxblox parameters
voxel_size: 0.1
truncation_distance: 0.2
max_weight: 100.0
esdf_update_rate: 2.0